<x-app-layout>
    <x-slot name="header">
        <div class="flex items-start justify-between gap-4"><div><div class="flex items-center gap-2"><h1 class="text-2xl font-bold text-gray-900 dark:text-white">{{ $collection->name }}</h1><span class="rounded-full bg-indigo-50 px-2 py-1 text-xs font-semibold text-indigo-700 dark:bg-indigo-950 dark:text-indigo-300">{{ ucfirst($membership->role) }}</span></div><p class="mt-1 text-sm text-gray-500">Owned by {{ $collection->owner->name }}</p></div>
        @if($membership->role !== 'owner')<form method="POST" action="{{ route('collections.leave', $collection) }}">@csrf @method('DELETE')<button class="text-sm font-semibold text-red-600">Leave collection</button></form>@endif</div>
    </x-slot>
    <div class="mx-auto max-w-6xl space-y-8 px-4 py-10 sm:px-6 lg:px-8">
        @if(session('success'))<div class="rounded-lg bg-green-50 px-4 py-3 text-sm text-green-800 dark:bg-green-950 dark:text-green-200">{{ session('success') }}</div>@endif
        @if(session('invite_url'))<div class="rounded-xl border border-indigo-200 bg-indigo-50 p-5 dark:border-indigo-800 dark:bg-indigo-950"><p class="text-sm font-semibold text-indigo-900 dark:text-indigo-100">Copy this invite link now</p><input readonly value="{{ session('invite_url') }}" class="mt-2 w-full rounded-lg border-indigo-200 bg-white text-sm dark:bg-gray-900"><p class="mt-2 text-xs text-indigo-700 dark:text-indigo-300">For security, the token is stored only as a hash and will not be shown again.</p></div>@endif
        @if($collection->description)<p class="text-gray-700 dark:text-gray-200">{{ $collection->description }}</p>@endif

        @can('update', $collection)
            <section class="grid gap-5 rounded-xl border border-gray-200 bg-white p-6 dark:border-gray-700 dark:bg-gray-800 lg:grid-cols-2">
                <form method="POST" action="{{ route('collections.update', $collection) }}" class="space-y-4">@csrf @method('PUT')<h2 class="font-semibold dark:text-white">Collection settings</h2><input name="name" value="{{ $collection->name }}" maxlength="120" required class="w-full rounded-lg border-gray-300 dark:border-gray-600 dark:bg-gray-900 dark:text-white"><textarea name="description" rows="3" maxlength="2000" class="w-full rounded-lg border-gray-300 dark:border-gray-600 dark:bg-gray-900 dark:text-white">{{ $collection->description }}</textarea><button class="rounded-lg bg-gray-900 px-4 py-2 text-sm font-semibold text-white dark:bg-gray-100 dark:text-gray-900">Save settings</button></form>
                <div><h2 class="font-semibold dark:text-white">Invite link</h2><p class="mt-1 text-sm text-gray-500">Generate a link that expires in seven days.</p><form method="POST" action="{{ route('collections.invite', $collection) }}" class="mt-4 flex gap-2">@csrf<select name="role" class="rounded-lg border-gray-300 dark:border-gray-600 dark:bg-gray-900 dark:text-white"><option value="viewer">Viewer</option><option value="editor">Editor</option></select><button class="rounded-lg bg-indigo-600 px-4 py-2 text-sm font-semibold text-white">Generate</button></form>@if($collection->invite_token_hash)<form method="POST" action="{{ route('collections.invite.destroy', $collection) }}" class="mt-3">@csrf @method('DELETE')<button class="text-sm font-semibold text-red-600">Revoke active invite</button></form>@endif</div>
            </section>
        @endcan

        @can('addPrompt', $collection)
            <section class="rounded-xl border border-gray-200 bg-white p-6 dark:border-gray-700 dark:bg-gray-800"><h2 class="font-semibold dark:text-white">Add one of your personal prompts</h2>@if($personalPrompts->isNotEmpty())<form method="POST" action="{{ route('collections.prompts.store', $collection) }}" class="mt-4 flex gap-2">@csrf<select name="prompt_id" class="min-w-0 flex-1 rounded-lg border-gray-300 dark:border-gray-600 dark:bg-gray-900 dark:text-white">@foreach($personalPrompts as $personalPrompt)<option value="{{ $personalPrompt->id }}">{{ $personalPrompt->title }}</option>@endforeach</select><button class="rounded-lg bg-indigo-600 px-4 py-2 text-sm font-semibold text-white">Add prompt</button></form>@else<p class="mt-2 text-sm text-gray-500">You have no unassigned personal prompts.</p>@endif</section>
        @endcan

        <section><h2 class="mb-4 text-lg font-bold dark:text-white">Prompts</h2><div class="grid gap-4 md:grid-cols-2">@forelse($collection->prompts as $prompt)<article class="rounded-xl border border-gray-200 bg-white p-5 dark:border-gray-700 dark:bg-gray-800"><a href="{{ route('prompts.show', $prompt) }}" class="font-bold text-gray-900 hover:text-indigo-600 dark:text-white">{{ $prompt->title }}</a><p class="mt-1 text-sm text-gray-500">{{ $prompt->target_model }} &middot; {{ $prompt->user->name }}</p><div class="mt-4 flex gap-3 text-sm font-semibold">@can('update', $prompt)<a href="{{ route('prompts.edit', $prompt) }}" class="text-indigo-600">Edit</a>@endcan @if($prompt->user_id === auth()->id() || $collection->owner_id === auth()->id())<form method="POST" action="{{ route('collections.prompts.destroy', [$collection, $prompt]) }}">@csrf @method('DELETE')<button class="text-red-600">Remove</button></form>@endif</div></article>@empty<p class="text-sm text-gray-500">No prompts have been added.</p>@endforelse</div></section>

        <section class="rounded-xl border border-gray-200 bg-white p-6 dark:border-gray-700 dark:bg-gray-800"><h2 class="font-semibold dark:text-white">Members</h2><div class="mt-4 divide-y divide-gray-200 dark:divide-gray-700">@foreach($collection->memberships as $member)<div class="flex flex-wrap items-center justify-between gap-3 py-3"><div><p class="font-medium dark:text-white">{{ $member->user->name }}</p><p class="text-xs text-gray-500">{{ $member->user->email }}</p></div>@can('manageMembers', $collection)@if($member->role !== 'owner')<div class="flex gap-2"><form method="POST" action="{{ route('collections.members.update', [$collection, $member->user_id]) }}" class="flex gap-2">@csrf @method('PATCH')<select name="role" class="rounded-lg border-gray-300 py-1 text-sm dark:border-gray-600 dark:bg-gray-900 dark:text-white"><option value="viewer" @selected($member->role === 'viewer')>Viewer</option><option value="editor" @selected($member->role === 'editor')>Editor</option></select><button class="text-sm font-semibold text-indigo-600">Save</button></form><form method="POST" action="{{ route('collections.members.destroy', [$collection, $member->user_id]) }}">@csrf @method('DELETE')<button class="text-sm font-semibold text-red-600">Remove</button></form></div>@else<span class="text-sm font-semibold text-gray-500">Owner</span>@endif @else<span class="text-sm capitalize text-gray-500">{{ $member->role }}</span>@endcan</div>@endforeach</div></section>
        @can('viewAudit', $collection)<div class="flex items-center justify-between"><a href="{{ route('collections.audit.index', $collection) }}" class="text-sm font-semibold text-indigo-600">View audit log</a><form method="POST" action="{{ route('collections.destroy', $collection) }}" x-data x-on:submit="if (! confirm('Delete this collection? Its prompts will become personal.')) $event.preventDefault()">@csrf @method('DELETE')<button class="text-sm font-semibold text-red-600">Delete collection</button></form></div>@endcan
    </div>
</x-app-layout>
